### ISSUE TITLE
Remove unneeded `extern crate serde`

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1026]
Since https://github.com/rust-lang/rust/pull/42588, Rust warns by default on unused extern crates. The readme example code, as well as possibly other examples in rustdoc, has `extern crate serde` but does not refer to anything from it. It is there as a reminder that the generated code requires serde to be listed as a dependency in Cargo.toml.

I imagine we can make up for it by providing an explicit Cargo.toml snippet instead.

```toml
[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
```
