### ISSUE TITLE
adjacently tagged enums with dynamic content name

### ISSUE THREAD

**Issue by clux** [serde-rs/serde#1343]
From [kubernetes documentation](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-custom-metrics), a variant on serde's adjacently tagged enums can be found:

```yaml
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Pods
    pods:
      metricName: packets-per-second
      targetAverageValue: 1k
```

These structs are generated in go via [kubernetes/.../types.go](https://github.com/kubernetes/kubernetes/blob/007bf90e32733286a5eb293b579db880a702eb5b/pkg/apis/autoscaling/types.go#L124-L152)
Which is doable in serde with plain tagged enums and wrapper structs using:

```rust
#[derive(Serialize, Deserialize, Clone)]
#[serde(tag = "type")]
pub enum ScalingMetric {
    Resource(ScalingMetricResourceWrapper),
    Pods(ScalingMetricPodWrapper),
}

#[derive(Serialize, Deserialize, Clone)]
pub struct ScalingMetricResourceWrapper { resource: ScalingMetricResource }
#[derive(Serialize, Deserialize, Clone)]
pub struct ScalingMetricPodWrapper { pods: ScalingMetricPod }
```

but a `#[serde(tag = "type", content = DYNAMIC)]` on the main enum would get rid of the need for wrapper structs. Is this a use case you think is worth supporting?
