### ISSUE TITLE
No method named serialize_field

### ISSUE THREAD

**Issue by jedmao** [serde-rs/serde#1687]
I'm just copying what's in the documentation, but I'm getting an error when I try to `serialize_field`, saying the following:

>no method named `serialize_field` found for type `<S as _IMPL_DESERIALIZE_FOR_EditorConfigINIAST::_serde::Serializer>::SerializeStruct` in the current scope

```rs
impl Serialize for Comment {
	fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
	where
		S: Serializer,
	{
		let mut state = serializer.serialize_struct("Comment", 3)?;
		state.serialize_field("type", "comment")?;
		state.serialize_field("indicator", &self.indicator)?;
		state.serialize_field("value", &self.value)?;
		state.end();
	}
}
```

My Cargo.toml has these lines in it:

```toml
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.42"
```
