### ISSUE TITLE
wasm-pack + serde + AtomicUsize 

### ISSUE THREAD

**Issue by gakonst** [serde-rs/serde#1778]
`Serialize` is not implemented for `AtomicUsize` in wasm when using [`wasm-pack`](https://github.com/rustwasm/wasm-pack).

Example:

1. Install `wasm-pack`: `curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh`

2. Add to your Cargo.toml:
```toml
[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
wasm-bindgen = "0.2.60"
```

3. Code:
```rust
use std::sync::atomic::AtomicUsize;
use serde::Serialize;

#[derive(Serialize)]
pub struct S(AtomicUsize);
```
4. Run `wasm-pack build` (`wasm-pack` builds into `wasm32-unknown-unknown`)

It errors with:
```
pub struct S(AtomicUsize);
  |              ^^^^^^^^^^^ the trait `_IMPL_SERIALIZE_FOR_S::_serde::Serialize` is not implemented for `std::sync::atomic::AtomicUsize
```

Could anybody explain to me why/if it is not fundamentally impossible to implement this?
