### ISSUE TITLE
Can not deserialize type with untagged enum with serde-json arbitary-precision enabled

### ISSUE THREAD

**Issue by runapp** [serde-rs/serde#1998]
( The issue content was completely rewritten, MWE at the end )

Derived deserializer of untagged enums uses `serde::__private::de::Content` to temporarily store deserialized data from `serde-json`, and uses `serde::__private::de::ContentRefDeserializer` to convert that to one of the enum's branches. And `serde-json` use a map to represent numbers when arbitary-precision is enabled, which `ContentRefDeserializer` has no idea of and thus reject to deserialize. 

Seems relating to https://github.com/serde-rs/json/issues/505

```rust
use serde::{Deserialize, Serialize};
#[derive(Serialize, Deserialize, Debug)]
#[serde(untagged)]
enum E {    A(i32),     }

fn main() {
    let e = E::A(10);
    let e_json = serde_json::to_string(&e).unwrap();
    println!("json: {}", &e_json);  # "10"
    if let Err(t_err) = serde_json::from_str::<E>(&e_json) {
        println!("err: {}", &t_err);
    }
}
```

```TOML
# Cargo.toml
[dependencies.serde]
package = "serde"
version = "=1.0.123"
features = ["derive", "rc"]

[dependencies.serde_json]
package = "serde_json"
version = "=1.0.64"
features = ["raw_value", "arbitrary_precision"]
path = "serde-json"
```
