### ISSUE TITLE
`Box<RawValue>` and `#[serde(flatten)]` don't work together for deserialization

### ISSUE THREAD

**Issue by tbu-** [serde-rs/serde#2213]
It seems that if any struct field in the path to a `Box<RawValue>` is marked with `#[serde(flatten)]`, deserialization **always** fails.

In the example below, `Def` can deserialize a certain JSON string, but the struct `Abc` containing a single `#[serde(flatten)]` `Def` field fails.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a7a182c5711834ea12a847374eb08de5

```
> cargo run
[…]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: newtype struct, expected any valid JSON value", line: 1, column: 11)', src/main.rs:19:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```rs
#![allow(dead_code)]

use serde::Deserialize;
use std::error::Error;

#[derive(Deserialize)]
struct Abc {
    #[serde(flatten)]
    pub def: Def,
}

#[derive(Deserialize)]
struct Def {
    pub ghi: Box<serde_json::value::RawValue>,
}

fn main() -> Result<(), Box<dyn Error>> {
    let _: Def = serde_json::from_str(r#"{"ghi": {}}"#).unwrap();
    let _: Abc = serde_json::from_str(r#"{"ghi": {}}"#).unwrap();
    Ok(())
}
```

```toml
[package]
name = "abc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_json = { version = "1.0.80", features = [
  "float_roundtrip",
  "preserve_order",
  "raw_value",
] }
```

Might have a similar root cause as #479, #545, #599 or #779.
