### ISSUE TITLE
serde_codegen: seems to overflow its stack on travis (via docker)

### ISSUE THREAD

**Issue by Byron** [serde-rs/serde#229]
When using serde on OSX on travis-ci in a docker container (the new default), [the build script](https://github.com/Byron/yup-oauth2/blob/9481e5cf405a62f209639a8f42b7491fce5d1a55/src/build.rs#L10) will [overflow its stack](https://travis-ci.org/Byron/yup-oauth2/jobs/107561589#L352).

This does not happen when using `serde_codegen` on a *real* OSX system.

## How to reproduce

One could fork [`yup-oauth`](https://github.com/Byron/yup-oauth2), setup travis for the fork, and reproduce it that way.

Otherwise, one can alter `.travis.yml` of this repository as follows:

```yml
os:
  - linux
  - osx  # enable osx
before_script:
# assure travis-cargo is working on osx (need different PATH)
- pip install 'travis-cargo<0.2' --user  && export PATH=$HOME/Library/Python/2.7/bin:$HOME/.local/bin:$PATH
```

## Meta

* related to [this issue](https://github.com/Byron/yup-oauth2/issues/16)
