### ISSUE TITLE
Map default features is not using BTreeMap

### ISSUE THREAD

**Issue by yosepalexsander** [serde-rs/serde#2397]
Everytime i add `serde_json` package with no features and try to serialize serde_json `Map<String, Value>`. It's not sort order by keys (because i saw the default is backed by BTreeMap).

```toml
async-trait = "0.1.63"
futures = "0.3"
serde = { version = "1.0.154", features = ["derive"] }
time = { version = "0.3", features = ["macros", "parsing", "serde"] }
tokio = { version = "1.24.2", features = ["full"] }
thiserror = "1.0.38"
awc = "3.1.0"
serde_qs = "0.11.0"
actix-web = "4.3.1"
mongodb = "2.4.0"
serde_json = "1.0.94"
```

Test function:
```rust
fn test_serialize_map() {
        let data = r#"
        {
            "name": "John Doe",
            "age": 4444,
            "phones": [
                "+44 1234567",
                "+44 2345678"
            ]
        }"#;
        let v: Map<String, Value> = serde_json::from_str(data).unwrap();
        println!(
            "{:#?}",
            serde_json::to_string::<Map<String, Value>>(&v).unwrap()
        );
    }
```

Result:
```
"{\"name\":\"John Doe\",\"age\":4444,\"phones\":[\"+44 1234567\",\"+44 2345678\"]}"
```

Expected result (using BTreeMap):
```
"{\"age\":4444,\"name\":\"John Doe\",\"phones\":[\"+44 1234567\",\"+44 2345678\"]}"
```
