### ISSUE TITLE
serde_derive will be found within precompiled/bin when using git

### ISSUE THREAD

**Issue by Astavie** [serde-rs/serde#2526]
I'm unsure if this is intentional or not, but I'm currently unable to use serde as a dependency like this:

```toml
[dependencies]
serde = { git = "https://github.com/serde-rs/serde.git", features = ["derive"] }
```

When doing that, I get these errors:

```
error: proc-macro derive panicked
   --> discord/src/gateway.rs:131:10
    |
131 | #[derive(Deserialize)]
    |          ^^^^^^^^^^^
    |
    = help: message: failed to spawn process: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

This is because it tries to run `serde_derive/serde_derive-x86_64-unknown-linux-gnu`, a binary that is not included in the git repo and is not built automatically. It seems that it finds `serde_derive` within `precompiled/bin/` before the it finds it in `serde_derive/`

This is does not happen when simply using the crates.io package, so this might seem inconsequential. However, this means it's harder to use serde forks as dependencies for testing purposes. I found this issue when trying to use my own fork:

```toml
[dependencies]
serde = { git = "https://github.com/Astavie/serde.git", branch = "integer-tags-for-enums", features = ["derive"] }
```

For now I have made another branch on my fork where I removed the precompiled folder, but it would be nice if this wasn't necessary.
