### ISSUE TITLE
"Inlining" enum into containing struct

### ISSUE THREAD

**Issue by jonas-schievink** [serde-rs/serde#761]
I'm trying to (de)serialize a TOML config which basically allows the user to choose a mode. It essentially looks like this:

```rust
struct Config {
    name: String,
    other_common_stuff: u64,
    mode: ConfigMode,
}

enum ConfigMode {
    Url {
        url: String,
    }
    
    Dummy {
        print: bool,
    }
}
```

I want the config file to look somewhat like this:

```toml
name = "bla"
other_common_stuff = 456
mode = "url"
url = "http://example.com"
```

Or, for selecting the `Dummy` mode:

```toml
name = "bla"
other_common_stuff = 456
mode = "dummy"
print = "Hello, World!"
```

So I basically need to "inline" the `ConfigMode` into the `Config` struct for (de)serialization. Since serde supports untagged enums, this doesn't seem too hard to implement to me, right?
